添加获取 BT 任务模式的函数
BITTORRENT_MODE 有三种结果，1、single：BT 任务，文件只有一个；2、multi：BT 任务，文件有多个；3、null：非 BT 任务

diff --git a/core b/core
--- a/core
+++ b/core
@@ -106,6 +106,14 @@ GET_TASK_INFO() {
     RPC_RESULT="$(RPC_TASK_INFO)"
 }
 
+GET_BITTORRENT_MODE() {
+    [[ -z ${RPC_RESULT} ]] && {
+        echo -e "$(DATE_TIME) ${ERROR} Aria2 RPC interface error!"
+        exit 1
+    }
+    BITTORRENT_MODE=$(echo "${RPC_RESULT}" | jq -r '.result.bittorrent.mode')    # single | multi | null
+}
+
 GET_DOWNLOAD_DIR() {
     [[ -z ${RPC_RESULT} ]] && {
         echo -e "$(DATE_TIME) ${ERROR} Aria2 RPC interface error!"
